export const Paths = {
    Home: "/",
    Search: "/tim-kiem",
    FavoriteProducts: "/san-pham-yeu-thich",
    ListProducts: "/list-san-pham",
    ProductDetail: "/san-pham-chi-tiet/:id",
    Blogs: "/bai-viet",
    BlogDetail: "/bai-viet-chi-tiet/:id",
    UserOrderDetail: "/don-hang-chi-tiet-cua-ban/:id",
    Profile: "/nguoi-dung",
    ChangePassword: "/profile/doi-mat-khau",
    UserOrders: "/don-hang-cua-ban",
    Cart: "/gio-hang",
    Checkout: "/thanh-toan",
    Bill: "/xuat-hoa-don",
    Introduce: "/gioi-thieu",
    Contact: "/lien-he",
    CustomerCare: "/cham-soc-khach-hang",
    QuestionAnswer: "/hoi-dap",
    Login: "/dang-nhap",
    Register: "/dang-ky",
    ForgetPassword: "/quen-mat-khau",
    Admin: {
      Dashboard: "/admin/trang-chu",
      Categories: "/admin/quan-li-loai/danh-muc-san-pham",
      Products: "/admin/quan-li-san-pham",
      ProductDetail: "/admin/quan-li-san-pham-chi-tiet/:id",
      AddProduct: "/admin/quan-li-san-pham/tao-san-pham-moi",
      EditProduct: "/admin/quan-li-san-pham/sua-san-pham/:id",
      ProductComments: "/admin/quan-li-san-pham/quan-li-binh-luan",
      Blogs: "/admin/quan-li-bai-viet",
      AddBlog: "/admin/quan-li-bai-viet/them-bai-viet-moi",
      EditBlog: "/admin/quan-li-bai-viet/sua-bai-viet/:id",
      BlogComments: "/admin/quan-li-bai-viet/quan-li-binh-luan-bai-viet",
      Customers: "/admin/quan-li-khach-hang",
      Staff: "/admin/quan-li-nhan-vien",
      AddStaff: "/admin/quan-li-nhan-vien/tao-nhan-vien-moi",
      EditStaff: "/admin/quan-li-nhan-vien/sua-nhan-vien/:id",
      Orders: "/admin/quan-li-don-hang",
      OrderDetail: "/admin/quan-li-don-hang-chi-tiet/:id",
      AddOrder: "/admin/quan-li-don-hang/tao-don-hang",
      EditOrder: "/admin/quan-li-don-hang/sua-don-hang/:id",
      Chat: "/admin/quan-li-tin-nhan",
      Settings: "/admin/quan-li-trang-web",
    },
  };
  